// front/react/src/components/header/Header.tsx
/* eslint-disable jsx-a11y/anchor-is-valid */
import './Header.scss';
import React, { useState } from 'react';
import { Helmet } from 'react-helmet';
import { NavLink } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faTint } from '@fortawesome/free-solid-svg-icons';

const Header: React.FC = () => {
  const [theme, setTheme] = useState('light');
  const switchTheme = () => setTheme(theme === 'light' ? 'dark' : 'light');

  return (
    <>
      <Helmet>
        <html lang="en" className={`theme--${theme}`} />
      </Helmet>

      <div className="header__logo">CW</div>

      <div className="header__menu">
        <NavLink
          exact
          className="header__menu-link"
          activeClassName="header__menu-link--active"
          to="/"
        >
          Home
        </NavLink>
        <NavLink
          className="header__menu-link"
          activeClassName="header__menu-link--active"
          to="/basic"
        >
          Basic
        </NavLink>
        <NavLink
          className="header__menu-link"
          activeClassName="header__menu-link--active"
          to="/mirror"
        >
          Mirror
        </NavLink>
        <NavLink
          className="header__menu-link"
          activeClassName="header__menu-link--active"
          to="/whiteboard"
        >
          Whiteboard
        </NavLink>
      </div>

      <div className="header__menu">
        <a
          href="#"
          className="header__menu-link header__menu-link--capitalize"
          onClick={switchTheme}
          onKeyDown={() => {}}
        >
          <FontAwesomeIcon className="header__menu-link-icon" icon={faTint} />
          <span className="header__menu-link-sm">{theme}</span>
        </a>
      </div>
    </>
  );
};

export default Header;

// front/src/app/layouts/header/header.component.ts
import { ThemeService } from 'src/app/services/theme.service';

import { Component, OnInit } from '@angular/core';
import { faTint } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
})
export class HeaderComponent implements OnInit {
  themeIcon = faTint;

  constructor(public themeService: ThemeService) {}

  ngOnInit() {}
}

<div class="logo" routerLink="/home">CW</div>

<div class="menu">
  <a class="menu-link" routerLinkActive="menu-link--active" routerLink="/home">Home</a>
  <a class="menu-link" routerLinkActive="menu-link--active" routerLink="/canvas-basic">Basic</a>
  <a class="menu-link" routerLinkActive="menu-link--active" routerLink="/canvas-mirror">Mirror</a>
  <a class="menu-link" routerLinkActive="menu-link--active" routerLink="/whiteboard">Whiteboard</a>
</div>

<div class="menu">
  <a class="menu-link menu-link--capitalize" (click)="themeService.switchTheme()">
    <fa-icon class="menu-link-icon" [icon]="themeIcon"></fa-icon>
    <span class="menu-link-sm">{{ themeService.name }}</span>
  </a>

  <!--<a class="menu-link">
    <fa-icon class="menu-link-icon" [icon]="userIcon" size="lg"></fa-icon>
    <span class="menu-link-sm">Profile</span>
  </a>-->
</div>
